app/models.py
from .import db
from . import login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Quote:
    '''
    Quote class to hold random quote
    '''

    def __init__(self, author, quote, permalink):
        self.author = author
        self.quote = quote
        self.permalink = permalink

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255), index = True)
    email = db.Column(db.String(255), unique = True, index = True)
    password_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String(255))
    blogs = db.relationship("Blog", backref= "user", lazy="dynamic")
    comments = db.relationship("Comment", backref= "user", lazy="dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.password_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_secure,password)    


    def __repr__(self):
        return f'User {self.username}'

class Blog(db.Model):
    __tablename__='blogs'

    id = db.Column(db.Integer,primary_key = True)
    blog_pic_path = db.Column(db.String(255))
    title = db.Column(db.String(255))
    message = db.Column(db.String(255))
    user_id =db.Column(db.Integer,db.ForeignKey("users.id"))
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    comments = db.relationship("Comment",backref = "blog",lazy = "dynamic")


    def delete_blog(self):
        db.session.delete(self)
        db.session.commit()

    def get_blog(self,id):
        blog = Blog.query.filter_by(id = self.id).first()
        comments = Comment.query.filter_by(blog_id = blog.id).order_by(Comment.posted.desc())
        return comments

class Comment(db.Model):
    __tablename__ ='comments'

    id = db.Column(db.Integer,primary_key = True)
    blog_id = db.Column(db.Integer,db.ForeignKey("blogs.id"))
    title = db.Column(db.String(255))
    comment = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(blog_id = id).all()
        return comments

    def delete_comment(self):
        db.session.delete(self)
        db.session.commit()

class Subscriber(db.Model):
    __tablename__ = 'subscribers'

    id = db.Column(db.Integer,primary_key = True)
    email = db.Column(db.String(255))
    username = db.Column(db.String(255),index = True)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,FileField,SubmitField
from wtforms.validators import Required

class CommentForm(FlaskForm):
    title = StringField('Comment title',validators= [Required()])
    comment = TextAreaField('Comment review')
    submit = SubmitField('submit')


class BlogForm(FlaskForm):
    title = StringField('Blog title',validators= [Required()]) 
    message = TextAreaField('Blog Message',validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about yourself',validators=[Required()])
    submit = SubmitField('submit')       

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_simplemde import SimpleMDE
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
#from flask_mail import Mail



login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
simple = SimpleMDE()
#mail = Mail()


def create_app(config_name):  # factory function
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    simple.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    #mail.init_app(app)

    # Registering the blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint , url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__) 

from . import views ,errors

app/main/views.py
from . import main
from flask import render_template,request,url_for,redirect,abort
from .. request import get_quote
from flask_login import login_required,current_user
from ..models import User,Comment,Blog,Subscriber
from .forms import BlogForm,CommentForm,UpdateProfile
from .. import db
import markdown2



@main.route('/')
def index():

    title = 'Developer Blog'
    quote = get_quote()
    blogs = Blog.query.all()
    
    return render_template('index.html', title=title,quote = quote,blogs = blogs)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    blogs = Blog.query.filter_by(user_id = user.id).order_by(Blog.date_posted.desc())

    if user is None:
        abort(404)

    return render_template('profile/profile.html',user = user,blogs =blogs)

@main.route('/user/<uname>/delete/<blog_id>')
@login_required
def del_blog(uname,blog_id):
    user = User.query.filter_by(username = uname).first()
    blogs = Blog.query.filter_by(user_id = user.id).order_by(Blog.date_posted.desc())
    blog = Blog.query.filter_by(id = blog_id).first()

    if blog.user_id == current_user.id:
        blog.delete_blog()

    return render_template("profile/profile.html",user = user,blogs = blogs) 

@main.route('/user/<uname>/update',methods = ['GET','POST'])  
@login_required
def update_profile(uname):
     user = User.query.filter_by(username = uname).first()
     if user is None:
         abort(404)
         
     form = UpdateProfile()

     if form.validate_on_submit():
          user.bio = form.bio.data

          db.session.add(user)
          db.session.commit()

          return redirect(url_for('.profile',uname = user.username))

     return render_template('profile/update.html',form = form,user = user)

@main.route('/user/<uname>/blog',methods =['GET','POST'])
@login_required
def new_blog(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = BlogForm()
    blog = Blog()

    if form.validate_on_submit():
        blog.title = form.title.data
        blog.message = form.message.data
        blog.user_id = current_user.id

        db.session.add(blog)
        db.session.commit()

        Subscribers = Subscriber.query.all()
       # mail_message("New Blog Post", "email/new_blog", subscriber.email, subscriber = subscriber)

        return redirect(url_for('.profile',uname=user.username))

    return render_template('new_blog.html',uname=uname, user = user, BlogForm = form)

@main.route('/comments/<blog_id>')
@login_required
def comments(blog_id):
    blog = Blog.query.filter_by(id = blog_id).first()
    comments = Comment.query.filter_by(blog_id = blog.id).order_by()


    return render_template('comments.html', blog = blog, comments = comments)

@main.route('/comment/delete/<blog_id>/<comment_id>')
@login_required
def del_comment(blog_id, comment_id):
    blog = Blog.query.filter_by(id = blog_id).first()
    comments = Comment.query.filter_by(blog_id = blog.id).order_by()
    comment = Comment.query.filter_by(id = comment_id).first()
    if blog.user_id == current_user.id or comment.user_id == current_user.id:

        Comment.delete_comment(comment)

    return render_template('comments.html', blog = blog, comments = comments)

@main.route('/blog/comment/new/<blog_id>', methods = ['GET', 'POST'])
@login_required
def new_review(blog_id):
    form = CommentForm()
    blog = Blog.query.filter_by(id = blog_id).first()
    comment = Comment()

    if form.validate_on_submit():
        comment.title = form.title.data
        comment.comment = form.comment.data
        comment.blog_id = blog_id
        comment.user_id = current_user.id

        db.session.add(comment)
        db.session.commit()

        return redirect(url_for('main.comments', blog_id=blog.id ))

    return render_template('new_comment.html', comment_form = form)    

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Navbar block  -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}


{%block styles %}
  {{super()}}
  {{ simplemde.css}}
  {{ simplemde.js }}
  <link href="https://fonts.googleapis.com/css?family=Cinzel|Libre+Baskerville|Merienda|ZCOOL+XiaoWei|Abril+Fatface|Merriweather|Playfair+Display|Yanone+Kaffeesatz" rel="stylesheet">
  <link rel="stylesheet" type= "text/css" href="{{ url_for('static', filename='style/style.css') }}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type= "text/css" href="{{ url_for('static', filename='style/style.css') }}">

{% endblock %}

app/templates/comments.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block content %}
    <div class="container" id="shown_comments" style="background-color: teal;">

      <div class="col-md-5">
          <div class="content-section" >
              <div class="card" style="background-color: transparent;">
                <div class="card-header" style="background-color: thistle;">
                  <span>{{blog.title}}</span>
                </div>
                <div class="card-body">
                  <p class="card-text">Thoughts on "{{blog.title}}" by {{blog.user.username}}</p>
                  <p>"{{blog.message}}"</p>
                </div>
          </div>
          </div>
      </div>

    <div class="col-md-7" id="reviews">
      <div class="class=">
        <h1>Reviews</h1>
          <hr>

          {% if comments %}
              {{macro.displayComments(comments)}}
              <a class="btn btn-success btn-lg text-center" href="/blog/comment/new/{{blog.id}}"> Write a comment</a>
          {% else%}
              <h3 class="text-center" >This blog has no comments </h3>
              <a class="btn btn-primary btn-lg text-center" href="/blog/comment/new/{{blog.id}}"> Write a comment</a>
          {% endif %}
      </div>
    </div>

    </div>


    </div>

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/macros.html
{% macro displayComments(comments) %}
    {% for comment in comments %}
    <table style="width:100%">
      <col width="100">
      <col width="160">
      <col width="60">
      <col width="60">
      <tr>
        <th>Title</th>
        <th>Comment</th>
        <th>User</th>
        <th>Delete</th>
      </tr>
      <tr>
        <td>{{comment.title}}</td>
        <td>{{comment.comment}}</td>
        <td>{{comment.user.username}}</td>
        <td><a href="{{url_for('main.del_comment',blog_id = comment.blog_id, comment_id = comment.id)}}"><button type="button" name="button" class="btn btn-warning">Delete Comment</button></a></td>
    <hr>  
    </tr>
    </table>
    <br>
    <br>
    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<div  class="behave">
    <div class="navbar navbar-inverse navbar-expand-md navbar-dark" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse" style="font-size: 20px;">
                    <ul class="nav navbar-nav navbar-left">
                            <li><a class="navbar-brand" href="/" style="font-size: 20px;">SHII'S BLOG </a></li>
                            {% if current_user.is_authenticated %}
                            <li><a  href="{{url_for('main.profile',uname=current_user.username)}}">{{current_user.username}}</a></li>
                             <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                             {% else %}
                             <li style="position: 200px;"><a href="{{url_for('auth.login')}}">Sign in</a></li>
                             {% endif %}
                             
                       </ul>
                        
                          
                    </ul>
                </div>
  
            </div>
        </div>
  
  </div>

app/templates/new_blog.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
  <h3> {{user.username| capitalize}} </h3>
  <h3>New Blog</h3>
  <div class="big">
    {{wtf.quick_form(BlogForm)}}
  </div>


</div>
{% endblock %}

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">

    

        <div class="col-md-8 big">

            {{ wtf.quick_form(comment_form) }}


            {{simplemde.load}}
        </div>



</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container" id="fun" style="background-color: thistle;">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4 marg2">
            <h3 class="text-center"> {{user.username| capitalize}} </h3>
            <br>
            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}

            <br>
            <p> {{user.username| capitalize}} has no bio </p>


            {% endif %}
            <br>

            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}"> <button type="button" name="button"
                    class="btn btn-success"> Edit User Profile </button></a></a>
            {% endif %}
        </div>
        <br>
        <!--Display profile photo-->
        <div class="col-md-5 marg3">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}

        </div>
        <br>
        <div class="col-md-3 marg">
            <a href="{{url_for('main.new_blog',uname=user.username)}}"> <button type="button" name="button"
                    class="btn btn-primary"> Add a New Blog</button></a>
        </div>
    </div>
    <h3 class="text-center">Blogs</h3>

    {% if blogs %}
    <div class="row ">
        {% for blog in blogs %}
        <div class="col-md-3 card-group">
            <h3 class="source-name">{{blog.title | upper}}</h3>
            <div class="white">
                <p>Posted by <strong> {{blog.user.username}}</strong></p>
                <br>
                <p>Date: <strong>{{blog.date_posted}}</strong></p>
                <br>
                <p>"{{blog.message}}"</p>
                <br>
                <a href="{{url_for('main.del_blog',uname=user.username, blog_id = blog.id)}}"><button type="button"
                        name="button" class="btn btn-success">Delete Blog </button></a>
            </div>
        </div>
        {% endfor %}
        <br>
        {% else %}
        <h2>You have no Blogs</h2>
        {% endif %}
    </div>



</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}

  <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
     <br>
    <input type="file"  name="photo" class="form-control" required>
    <br>
    <input type="submit">
  </form>
</div>
{% endblock %}